package org.alviino.pokesim;

public enum Species  {
	
	DUMMY     (new Type[] {Type.NONE    , Type.NONE    },9999, 1  , 100, new BasicMove[] {BasicMove.DUMMY_ATTACK                                 }, new ChargeMove[] {ChargeMove.DUMMY_ATTACK                                                                                                                                                                                }),
	ABRA      (new Type[] {Type.PSYCHIC , Type.NONE    }, 50 , 110, 76 , new BasicMove[] {BasicMove.ZEN_HEADBUTT                                 }, new ChargeMove[] {ChargeMove.PSYSHOCK      , ChargeMove.SHADOW_BALL         , ChargeMove.SIGNAL_BEAM                                                                                                                     }),
	AERODACTYL(new Type[] {Type.ROCK    , Type.FLYING  }, 160, 182, 162, new BasicMove[] {BasicMove.BITE          , BasicMove.STEEL_WING         }, new ChargeMove[] {ChargeMove.ANCIENT_POWER , ChargeMove.HYPER_BEAM          , ChargeMove.IRON_HEAD                                                                                                                       }),
	ALAKAZAM  (new Type[] {Type.PSYCHIC , Type.NONE    }, 110, 186, 152, new BasicMove[] {BasicMove.CONFUSION     , BasicMove.PSYCHO_CUT         }, new ChargeMove[] {ChargeMove.DAZZLING_GLEAM, ChargeMove.PSYCHIC             , ChargeMove.SHADOW_BALL                                                                                                                     }),
	ARBOK     (new Type[] {Type.POISON  , Type.NONE    }, 120, 166, 166, new BasicMove[] {BasicMove.ACID          , BasicMove.BITE               }, new ChargeMove[] {ChargeMove.DARK_PULSE    , ChargeMove.GUNK_SHOT           , ChargeMove.SLUDGE_WAVE                                                                                                                     }),
	ARCANINE  (new Type[] {Type.FIRE    , Type.NONE    }, 180, 230, 180, new BasicMove[] {BasicMove.BITE          , BasicMove.FIRE_FANG          }, new ChargeMove[] {ChargeMove.BULLDOZE      , ChargeMove.FIRE_BLAST          , ChargeMove.FLAMETHROWER                                                                                                                    }),
	ARTICUNO  (new Type[] {Type.ICE     , Type.FLYING  }, 180, 198, 242, new BasicMove[] {BasicMove.FROST_BREATH                                 }, new ChargeMove[] {ChargeMove.BLIZZARD      , ChargeMove.ICE_BEAM            , ChargeMove.ICY_WIND                                                                                                                        }),
	BEEDRILL  (new Type[] {Type.BUG     , Type.POISON  }, 130, 144, 130, new BasicMove[] {BasicMove.BUG_BITE      , BasicMove.POISON_JAB         }, new ChargeMove[] {ChargeMove.AERIAL_ACE    , ChargeMove.SLUDGE_BOMB         , ChargeMove.X_SCISSOR                                                                                                                       }),
	BELLSPROUT(new Type[] {Type.GRASS   , Type.POISON  }, 100, 158, 78 , new BasicMove[] {BasicMove.ACID          , BasicMove.VINE_WHIP          }, new ChargeMove[] {ChargeMove.POWER_WHIP    , ChargeMove.SLUDGE_BOMB         , ChargeMove.WRAP                                                                                                                            }),
	BLASTOISE (new Type[] {Type.WATER   , Type.NONE    }, 158, 186, 222, new BasicMove[] {BasicMove.BITE          , BasicMove.WATER_GUN_BLASTOISE}, new ChargeMove[] {ChargeMove.FLASH_CANNON  , ChargeMove.HYDRO_PUMP_BLASTOISE, ChargeMove.ICE_BEAM                                                                                                                        }),
	BULBASAUR (new Type[] {Type.GRASS   , Type.POISON  }, 90 , 126, 126, new BasicMove[] {BasicMove.TACKLE        , BasicMove.VINE_WHIP          }, new ChargeMove[] {ChargeMove.POWER_WHIP    , ChargeMove.SEED_BOMB           , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	BUTTERFREE(new Type[] {Type.BUG     , Type.FLYING  }, 120, 144, 144, new BasicMove[] {BasicMove.BUG_BITE      , BasicMove.CONFUSION          }, new ChargeMove[] {ChargeMove.BUG_BUZZ      , ChargeMove.PSYCHIC             , ChargeMove.SIGNAL_BEAM                                                                                                                     }),
	CATERPIE  (new Type[] {Type.BUG     , Type.NONE    }, 90 , 62 , 66 , new BasicMove[] {BasicMove.BUG_BITE      , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.STRUGGLE                                                                                                                                                                                    }),
	CHANSEY   (new Type[] {Type.NORMAL  , Type.NONE    }, 500, 40 , 60 , new BasicMove[] {BasicMove.POUND         , BasicMove.ZEN_HEADBUTT       }, new ChargeMove[] {ChargeMove.DAZZLING_GLEAM, ChargeMove.HYPER_BEAM          , ChargeMove.PSYCHIC                                                                                                                         }),
	CHARIZARD (new Type[] {Type.FIRE    , Type.FLYING  }, 156, 212, 182, new BasicMove[] {BasicMove.EMBER         , BasicMove.WING_ATTACK        }, new ChargeMove[] {ChargeMove.DRAGON_CLAW   , ChargeMove.FIRE_BLAST          , ChargeMove.FLAMETHROWER                                                                                                                    }),
	CHARMANDER(new Type[] {Type.FIRE    , Type.NONE    }, 78 , 128, 108, new BasicMove[] {BasicMove.EMBER         , BasicMove.SCRATCH            }, new ChargeMove[] {ChargeMove.FLAME_BURST   , ChargeMove.FLAME_CHARGE        , ChargeMove.FLAMETHROWER                                                                                                                    }),
	CHARMELEON(new Type[] {Type.FIRE    , Type.NONE    }, 116, 160, 140, new BasicMove[] {BasicMove.EMBER         , BasicMove.SCRATCH            }, new ChargeMove[] {ChargeMove.FIRE_PUNCH    , ChargeMove.FLAME_BURST         , ChargeMove.FLAMETHROWER                                                                                                                    }),
	CLEFABLE  (new Type[] {Type.FAIRY   , Type.NONE    }, 190, 178, 178, new BasicMove[] {BasicMove.POUND         , BasicMove.ZEN_HEADBUTT       }, new ChargeMove[] {ChargeMove.DAZZLING_GLEAM, ChargeMove.MOONBLAST           , ChargeMove.PSYCHIC                                                                                                                         }),
	CLEFAIRY  (new Type[] {Type.FAIRY   , Type.NONE    }, 140, 116, 124, new BasicMove[] {BasicMove.POUND         , BasicMove.ZEN_HEADBUTT       }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.DISARMING_VOICE     , ChargeMove.MOONBLAST                                                                                                                       }),
	CLOYSTER  (new Type[] {Type.WATER   , Type.ICE     }, 100, 196, 196, new BasicMove[] {BasicMove.FROST_BREATH  , BasicMove.ICE_SHARD          }, new ChargeMove[] {ChargeMove.BLIZZARD      , ChargeMove.HYDRO_PUMP          , ChargeMove.ICY_WIND                                                                                                                        }),
	CUBONE    (new Type[] {Type.GROUND  , Type.NONE    }, 100, 102, 150, new BasicMove[] {BasicMove.MUD_SLAP      , BasicMove.ROCK_SMASH         }, new ChargeMove[] {ChargeMove.BONE_CLUB     , ChargeMove.BULLDOZE            , ChargeMove.DIG                                                                                                                             }),
	DEWGONG   (new Type[] {Type.WATER   , Type.ICE     }, 180, 156, 192, new BasicMove[] {BasicMove.FROST_BREATH  , BasicMove.ICE_SHARD          }, new ChargeMove[] {ChargeMove.AQUA_JET      , ChargeMove.BLIZZARD            , ChargeMove.ICY_WIND                                                                                                                        }),
	DIGLETT   (new Type[] {Type.GROUND  , Type.NONE    }, 20 , 108, 86 , new BasicMove[] {BasicMove.MUD_SLAP      , BasicMove.SCRATCH            }, new ChargeMove[] {ChargeMove.DIG           , ChargeMove.MUD_BOMB            , ChargeMove.ROCK_TOMB                                                                                                                       }),
	DITTO     (new Type[] {Type.NORMAL  , Type.NONE    }, 96 , 110, 110, new BasicMove[] {BasicMove.POUND                                        }, new ChargeMove[] {ChargeMove.STRUGGLE                                                                                                                                                                                    }),
	DODRIO    (new Type[] {Type.NORMAL  , Type.FLYING  }, 120, 182, 150, new BasicMove[] {BasicMove.FEINT_ATTACK  , BasicMove.STEEL_WING         }, new ChargeMove[] {ChargeMove.AERIAL_ACE    , ChargeMove.AIR_CUTTER          , ChargeMove.DRILL_PECK                                                                                                                      }),
	DODUO     (new Type[] {Type.NORMAL  , Type.FLYING  }, 70 , 126, 96 , new BasicMove[] {BasicMove.PECK          , BasicMove.QUICK_ATTACK       }, new ChargeMove[] {ChargeMove.AERIAL_ACE    , ChargeMove.DRILL_PECK          , ChargeMove.SWIFT                                                                                                                           }),
	DRAGONAIR (new Type[] {Type.DRAGON  , Type.NONE    }, 122, 170, 152, new BasicMove[] {BasicMove.DRAGON_BREATH                                }, new ChargeMove[] {ChargeMove.AQUA_TAIL     , ChargeMove.DRAGON_PULSE        , ChargeMove.WRAP                                                                                                                            }),
	DRAGONITE (new Type[] {Type.DRAGON  , Type.FLYING  }, 182, 250, 212, new BasicMove[] {BasicMove.DRAGON_BREATH , BasicMove.STEEL_WING         }, new ChargeMove[] {ChargeMove.DRAGON_CLAW   , ChargeMove.DRAGON_PULSE        , ChargeMove.HYPER_BEAM                                                                                                                      }),
	DRATINI   (new Type[] {Type.DRAGON  , Type.NONE    }, 82 , 128, 110, new BasicMove[] {BasicMove.DRAGON_BREATH                                }, new ChargeMove[] {ChargeMove.AQUA_TAIL     , ChargeMove.TWISTER             , ChargeMove.WRAP                                                                                                                            }),
	DROWZEE   (new Type[] {Type.PSYCHIC , Type.NONE    }, 120, 104, 140, new BasicMove[] {BasicMove.CONFUSION     , BasicMove.POUND              }, new ChargeMove[] {ChargeMove.PSYBEAM       , ChargeMove.PSYCHIC             , ChargeMove.PSYSHOCK                                                                                                                        }),
	DUGTRIO   (new Type[] {Type.GROUND  , Type.NONE    }, 70 , 148, 140, new BasicMove[] {BasicMove.MUD_SLAP      , BasicMove.SUCKER_PUNCH       }, new ChargeMove[] {ChargeMove.EARTHQUAKE    , ChargeMove.MUD_BOMB            , ChargeMove.STONE_EDGE                                                                                                                      }),
	EEVEE     (new Type[] {Type.NORMAL  , Type.NONE    }, 110, 114, 128, new BasicMove[] {BasicMove.QUICK_ATTACK  , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.DIG                 , ChargeMove.SWIFT                                                                                                                           }),
	EKANS     (new Type[] {Type.POISON  , Type.NONE    }, 70 , 112, 112, new BasicMove[] {BasicMove.ACID          , BasicMove.POISON_STING       }, new ChargeMove[] {ChargeMove.GUNK_SHOT     , ChargeMove.SLUDGE_BOMB         , ChargeMove.WRAP                                                                                                                            }),
	ELECTABUZZ(new Type[] {Type.ELECTRIC, Type.NONE    }, 130, 198, 160, new BasicMove[] {BasicMove.LOW_KICK      , BasicMove.THUNDER_SHOCK      }, new ChargeMove[] {ChargeMove.THUNDER       , ChargeMove.THUNDER_PUNCH       , ChargeMove.THUNDERBOLT                                                                                                                     }),
	ELECTRODE (new Type[] {Type.ELECTRIC, Type.NONE    }, 120, 150, 174, new BasicMove[] {BasicMove.SPARK         , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.DISCHARGE     , ChargeMove.HYPER_BEAM          , ChargeMove.THUNDERBOLT                                                                                                                     }),
	EXEGGCUTE (new Type[] {Type.GRASS   , Type.PSYCHIC }, 120, 110, 132, new BasicMove[] {BasicMove.CONFUSION                                    }, new ChargeMove[] {ChargeMove.ANCIENT_POWER , ChargeMove.PSYCHIC             , ChargeMove.SEED_BOMB                                                                                                                       }),
	EXEGGUTOR (new Type[] {Type.GRASS   , Type.PSYCHIC }, 190, 232, 164, new BasicMove[] {BasicMove.CONFUSION     , BasicMove.ZEN_HEADBUTT       }, new ChargeMove[] {ChargeMove.PSYCHIC       , ChargeMove.SEED_BOMB           , ChargeMove.SOLAR_BEAM                                                                                                                      }),
	FARFETCH_D(new Type[] {Type.NORMAL  , Type.FLYING  }, 104, 138, 132, new BasicMove[] {BasicMove.CUT           , BasicMove.FURY_CUTTER        }, new ChargeMove[] {ChargeMove.AERIAL_ACE    , ChargeMove.AIR_CUTTER          , ChargeMove.LEAF_BLADE                                                                                                                      }),
	FEAROW    (new Type[] {Type.NORMAL  , Type.FLYING  }, 130, 168, 146, new BasicMove[] {BasicMove.PECK          , BasicMove.STEEL_WING         }, new ChargeMove[] {ChargeMove.AERIAL_ACE    , ChargeMove.DRILL_RUN           , ChargeMove.TWISTER                                                                                                                         }),
	FLAREON   (new Type[] {Type.FIRE    , Type.NONE    }, 130, 238, 178, new BasicMove[] {BasicMove.EMBER                                        }, new ChargeMove[] {ChargeMove.FIRE_BLAST    , ChargeMove.FLAMETHROWER        , ChargeMove.HEAT_WAVE                                                                                                                       }),
	GASTLY    (new Type[] {Type.GHOST   , Type.POISON  }, 60 , 136, 82 , new BasicMove[] {BasicMove.LICK          , BasicMove.SUCKER_PUNCH       }, new ChargeMove[] {ChargeMove.DARK_PULSE    , ChargeMove.OMINOUS_WIND        , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	GENGAR    (new Type[] {Type.GHOST   , Type.POISON  }, 120, 204, 156, new BasicMove[] {BasicMove.SHADOW_CLAW   , BasicMove.SUCKER_PUNCH       }, new ChargeMove[] {ChargeMove.DARK_PULSE    , ChargeMove.SHADOW_BALL         , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	GEODUDE   (new Type[] {Type.ROCK    , Type.GROUND  }, 80 , 106, 118, new BasicMove[] {BasicMove.ROCK_THROW    , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.DIG           , ChargeMove.ROCK_SLIDE          , ChargeMove.ROCK_TOMB                                                                                                                       }),
	GLOOM     (new Type[] {Type.GRASS   , Type.POISON  }, 120, 162, 158, new BasicMove[] {BasicMove.ACID          , BasicMove.RAZOR_LEAF         }, new ChargeMove[] {ChargeMove.MOONBLAST     , ChargeMove.PETAL_BLIZZARD      , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	GOLBAT    (new Type[] {Type.POISON  , Type.FLYING  }, 150, 164, 164, new BasicMove[] {BasicMove.BITE          , BasicMove.WING_ATTACK        }, new ChargeMove[] {ChargeMove.AIR_CUTTER    , ChargeMove.OMINOUS_WIND        , ChargeMove.POISON_FANG                                                                                                                     }),
	GOLDEEN   (new Type[] {Type.WATER   , Type.NONE    }, 90 , 112, 126, new BasicMove[] {BasicMove.MUD_SHOT      , BasicMove.PECK               }, new ChargeMove[] {ChargeMove.AQUA_TAIL     , ChargeMove.HORN_ATTACK         , ChargeMove.WATER_PULSE                                                                                                                     }),
	GOLDUCK   (new Type[] {Type.WATER   , Type.NONE    }, 160, 194, 176, new BasicMove[] {BasicMove.CONFUSION     , BasicMove.WATER_GUN          }, new ChargeMove[] {ChargeMove.HYDRO_PUMP    , ChargeMove.ICE_BEAM            , ChargeMove.PSYCHIC                                                                                                                         }),
	GOLEM     (new Type[] {Type.ROCK    , Type.GROUND  }, 160, 176, 198, new BasicMove[] {BasicMove.MUD_SLAP      , BasicMove.ROCK_THROW         }, new ChargeMove[] {ChargeMove.ANCIENT_POWER , ChargeMove.EARTHQUAKE          , ChargeMove.STONE_EDGE                                                                                                                      }),
	GRAVELER  (new Type[] {Type.ROCK    , Type.GROUND  }, 110, 142, 156, new BasicMove[] {BasicMove.MUD_SLAP      , BasicMove.ROCK_THROW         }, new ChargeMove[] {ChargeMove.DIG           , ChargeMove.ROCK_SLIDE          , ChargeMove.STONE_EDGE                                                                                                                      }),
	GRIMER    (new Type[] {Type.POISON  , Type.NONE    }, 160, 124, 110, new BasicMove[] {BasicMove.POISON_JAB    , BasicMove.MUD_SLAP           }, new ChargeMove[] {ChargeMove.MUD_BOMB      , ChargeMove.SLUDGE              , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	GROWLITHE (new Type[] {Type.FIRE    , Type.NONE    }, 110, 156, 110, new BasicMove[] {BasicMove.BITE          , BasicMove.EMBER              }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.FLAME_WHEEL         , ChargeMove.FLAMETHROWER                                                                                                                    }),
	GYARADOS  (new Type[] {Type.WATER   , Type.FLYING  }, 190, 192, 196, new BasicMove[] {BasicMove.BITE                                         }, new ChargeMove[] {ChargeMove.DRAGON_PULSE  , ChargeMove.HYDRO_PUMP          , ChargeMove.TWISTER                                                                                                                         }),
	HAUNTER   (new Type[] {Type.GHOST   , Type.POISON  }, 90 , 172, 118, new BasicMove[] {BasicMove.LICK          , BasicMove.SHADOW_CLAW        }, new ChargeMove[] {ChargeMove.DARK_PULSE    , ChargeMove.SHADOW_BALL         , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	HITMONCHAN(new Type[] {Type.FIGHTING, Type.NONE    }, 100, 138, 204, new BasicMove[] {BasicMove.BULLET_PUNCH  , BasicMove.ROCK_SMASH         }, new ChargeMove[] {ChargeMove.BRICK_BREAK   , ChargeMove.FIRE_PUNCH          , ChargeMove.ICE_PUNCH      , ChargeMove.THUNDER_PUNCH                                                                                       }),
	HITMONLEE (new Type[] {Type.FIGHTING, Type.NONE    }, 100, 148, 172, new BasicMove[] {BasicMove.LOW_KICK      , BasicMove.ROCK_SMASH         }, new ChargeMove[] {ChargeMove.LOW_SWEEP     , ChargeMove.BRICK_BREAK         , ChargeMove.STONE_EDGE                                                                                                                      }),
	HORSEA    (new Type[] {Type.WATER   , Type.NONE    }, 60 , 122, 100, new BasicMove[] {BasicMove.BUBBLE        , BasicMove.WATER_GUN          }, new ChargeMove[] {ChargeMove.BUBBLE_BEAM   , ChargeMove.DRAGON_PULSE        , ChargeMove.FLASH_CANNON                                                                                                                    }),
	HYPNO     (new Type[] {Type.PSYCHIC , Type.NONE    }, 170, 162, 196, new BasicMove[] {BasicMove.CONFUSION     , BasicMove.ZEN_HEADBUTT       }, new ChargeMove[] {ChargeMove.PSYCHIC       , ChargeMove.PSYSHOCK            , ChargeMove.SHADOW_BALL                                                                                                                     }),
	IVYSAUR   (new Type[] {Type.GRASS   , Type.POISON  }, 120, 156, 158, new BasicMove[] {BasicMove.RAZOR_LEAF    , BasicMove.VINE_WHIP          }, new ChargeMove[] {ChargeMove.POWER_WHIP    , ChargeMove.SLUDGE_BOMB         , ChargeMove.SOLAR_BEAM                                                                                                                      }),
	JIGGLYPUFF(new Type[] {Type.NORMAL  , Type.FAIRY   }, 230, 98 , 54 , new BasicMove[] {BasicMove.FEINT_ATTACK  , BasicMove.POUND              }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.DISARMING_VOICE     , ChargeMove.DAZZLING_GLEAM                                                                                                                  }),
	JOLTEON   (new Type[] {Type.ELECTRIC, Type.NONE    }, 130, 192, 174, new BasicMove[] {BasicMove.THUNDER_SHOCK                                }, new ChargeMove[] {ChargeMove.DISCHARGE     , ChargeMove.THUNDER             , ChargeMove.THUNDERBOLT                                                                                                                     }),
	JYNX      (new Type[] {Type.ICE     , Type.PSYCHIC }, 130, 172, 134, new BasicMove[] {BasicMove.FROST_BREATH  , BasicMove.POUND              }, new ChargeMove[] {ChargeMove.DRAINING_KISS , ChargeMove.ICE_PUNCH           , ChargeMove.PSYSHOCK                                                                                                                        }),
	KABUTO    (new Type[] {Type.ROCK    , Type.WATER   }, 60 , 148, 142, new BasicMove[] {BasicMove.MUD_SHOT      , BasicMove.SCRATCH            }, new ChargeMove[] {ChargeMove.ANCIENT_POWER , ChargeMove.AQUA_JET            , ChargeMove.ROCK_TOMB                                                                                                                       }),
	KABUTOPS  (new Type[] {Type.ROCK    , Type.WATER   }, 120, 190, 190, new BasicMove[] {BasicMove.FURY_CUTTER   , BasicMove.MUD_SHOT           }, new ChargeMove[] {ChargeMove.ANCIENT_POWER , ChargeMove.STONE_EDGE          , ChargeMove.WATER_PULSE                                                                                                                     }),
	KADABRA   (new Type[] {Type.PSYCHIC , Type.NONE    }, 80 , 150, 112, new BasicMove[] {BasicMove.CONFUSION     , BasicMove.PSYCHO_CUT         }, new ChargeMove[] {ChargeMove.DAZZLING_GLEAM, ChargeMove.PSYBEAM             , ChargeMove.SHADOW_BALL                                                                                                                     }),
	KAKUNA    (new Type[] {Type.BUG     , Type.POISON  }, 90 , 62 , 82 , new BasicMove[] {BasicMove.BUG_BITE      , BasicMove.POISON_STING       }, new ChargeMove[] {ChargeMove.STRUGGLE                                                                                                                                                                                    }),
	KANGASKHAN(new Type[] {Type.NORMAL  , Type.NONE    }, 210, 142, 178, new BasicMove[] {BasicMove.LOW_KICK      , BasicMove.MUD_SLAP           }, new ChargeMove[] {ChargeMove.BRICK_BREAK   , ChargeMove.EARTHQUAKE          , ChargeMove.STOMP                                                                                                                           }),
	KINGLER   (new Type[] {Type.WATER   , Type.NONE    }, 110, 178, 168, new BasicMove[] {BasicMove.METAL_CLAW    , BasicMove.MUD_SHOT           }, new ChargeMove[] {ChargeMove.VICE_GRIP     , ChargeMove.WATER_PULSE         , ChargeMove.X_SCISSOR                                                                                                                       }),
	KOFFING   (new Type[] {Type.POISON  , Type.NONE    }, 80 , 136, 142, new BasicMove[] {BasicMove.TACKLE                                       }, new ChargeMove[] {ChargeMove.DARK_PULSE    , ChargeMove.SLUDGE              , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	KRABBY    (new Type[] {Type.WATER   , Type.NONE    }, 60 , 116, 110, new BasicMove[] {BasicMove.BUBBLE        , BasicMove.MUD_SHOT           }, new ChargeMove[] {ChargeMove.BUBBLE_BEAM   , ChargeMove.VICE_GRIP           , ChargeMove.WATER_PULSE                                                                                                                     }),
	LAPRAS    (new Type[] {Type.WATER   , Type.ICE     }, 260, 186, 190, new BasicMove[] {BasicMove.FROST_BREATH  , BasicMove.ICE_SHARD          }, new ChargeMove[] {ChargeMove.BLIZZARD      , ChargeMove.DRAGON_PULSE        , ChargeMove.ICE_BEAM                                                                                                                        }),
	LICKITUNG (new Type[] {Type.NORMAL  , Type.NONE    }, 180, 126, 160, new BasicMove[] {BasicMove.LICK          , BasicMove.ZEN_HEADBUTT       }, new ChargeMove[] {ChargeMove.HYPER_BEAM    , ChargeMove.POWER_WHIP          , ChargeMove.STOMP                                                                                                                           }),
	MACHAMP   (new Type[] {Type.FIGHTING, Type.NONE    }, 180, 198, 180, new BasicMove[] {BasicMove.BULLET_PUNCH  , BasicMove.KARATE_CHOP        }, new ChargeMove[] {ChargeMove.CROSS_CHOP    , ChargeMove.STONE_EDGE          , ChargeMove.SUBMISSION                                                                                                                      }),
	MACHOKE   (new Type[] {Type.FIGHTING, Type.NONE    }, 160, 154, 144, new BasicMove[] {BasicMove.KARATE_CHOP   , BasicMove.LOW_KICK           }, new ChargeMove[] {ChargeMove.BRICK_BREAK   , ChargeMove.CROSS_CHOP          , ChargeMove.SUBMISSION                                                                                                                      }),
	MACHOP    (new Type[] {Type.FIGHTING, Type.NONE    }, 140, 118, 96 , new BasicMove[] {BasicMove.KARATE_CHOP   , BasicMove.LOW_KICK           }, new ChargeMove[] {ChargeMove.BRICK_BREAK   , ChargeMove.CROSS_CHOP          , ChargeMove.LOW_SWEEP                                                                                                                       }),
	MAGIKARP  (new Type[] {Type.WATER   , Type.NONE    }, 40 , 42 , 84 , new BasicMove[] {BasicMove.SPLASH                                       }, new ChargeMove[] {ChargeMove.STRUGGLE                                                                                                                                                                                    }),
	MAGMAR    (new Type[] {Type.FIRE    , Type.NONE    }, 130, 214, 158, new BasicMove[] {BasicMove.EMBER         , BasicMove.KARATE_CHOP        }, new ChargeMove[] {ChargeMove.FIRE_BLAST    , ChargeMove.FIRE_PUNCH          , ChargeMove.FLAMETHROWER                                                                                                                    }),
	MAGNEMITE (new Type[] {Type.ELECTRIC, Type.STEEL   }, 50 , 128, 138, new BasicMove[] {BasicMove.SPARK         , BasicMove.THUNDER_SHOCK      }, new ChargeMove[] {ChargeMove.DISCHARGE     , ChargeMove.MAGNET_BOMB         , ChargeMove.THUNDERBOLT                                                                                                                     }),
	MAGNETON  (new Type[] {Type.ELECTRIC, Type.STEEL   }, 100, 186, 180, new BasicMove[] {BasicMove.SPARK         , BasicMove.THUNDER_SHOCK      }, new ChargeMove[] {ChargeMove.DISCHARGE     , ChargeMove.FLASH_CANNON        , ChargeMove.MAGNET_BOMB                                                                                                                     }),
	MANKEY    (new Type[] {Type.FIGHTING, Type.NONE    }, 80 , 122, 96 , new BasicMove[] {BasicMove.KARATE_CHOP   , BasicMove.SCRATCH            }, new ChargeMove[] {ChargeMove.BRICK_BREAK   , ChargeMove.CROSS_CHOP          , ChargeMove.LOW_SWEEP                                                                                                                       }),
	MAROWAK   (new Type[] {Type.GROUND  , Type.NONE    }, 120, 140, 202, new BasicMove[] {BasicMove.MUD_SLAP      , BasicMove.ROCK_SMASH         }, new ChargeMove[] {ChargeMove.BONE_CLUB     , ChargeMove.DIG                 , ChargeMove.EARTHQUAKE                                                                                                                      }),
	MEOWTH    (new Type[] {Type.NORMAL  , Type.NONE    }, 80 , 104, 94 , new BasicMove[] {BasicMove.BITE          , BasicMove.SCRATCH            }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.DARK_PULSE          , ChargeMove.NIGHT_SLASH                                                                                                                     }),
	METAPOD   (new Type[] {Type.BUG     , Type.NONE    }, 100, 56 , 86 , new BasicMove[] {BasicMove.BUG_BITE      , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.STRUGGLE                                                                                                                                                                                    }),
	MEW       (new Type[] {Type.PSYCHIC , Type.NONE    }, 200, 220, 220, new BasicMove[] {BasicMove.POUND                                        }, new ChargeMove[] {ChargeMove.DRAGON_PULSE  , ChargeMove.EARTHQUAKE          , ChargeMove.FIRE_BLAST     , ChargeMove.BLIZZARD      , ChargeMove.HYPER_BEAM, ChargeMove.PSYCHIC, ChargeMove.SOLAR_BEAM, ChargeMove.THUNDER}),
	MEWTWO    (new Type[] {Type.PSYCHIC , Type.NONE    }, 212, 284, 202, new BasicMove[] {BasicMove.CONFUSION     , BasicMove.PSYCHO_CUT         }, new ChargeMove[] {ChargeMove.HYPER_BEAM    , ChargeMove.PSYCHIC             , ChargeMove.SHADOW_BALL                                                                                                                     }),
	MOLTRES   (new Type[] {Type.FIRE    , Type.FLYING  }, 180, 242, 194, new BasicMove[] {BasicMove.EMBER                                        }, new ChargeMove[] {ChargeMove.FIRE_BLAST    , ChargeMove.FLAMETHROWER        , ChargeMove.HEAT_WAVE                                                                                                                       }),
	MR_MIME   (new Type[] {Type.PSYCHIC , Type.NONE    }, 80 , 154, 196, new BasicMove[] {BasicMove.CONFUSION     , BasicMove.ZEN_HEADBUTT       }, new ChargeMove[] {ChargeMove.PSYBEAM       , ChargeMove.PSYCHIC             , ChargeMove.SHADOW_BALL                                                                                                                     }),
	MUK       (new Type[] {Type.POISON  , Type.NONE    }, 210, 180, 188, new BasicMove[] {BasicMove.LICK          , BasicMove.POISON_JAB         }, new ChargeMove[] {ChargeMove.DARK_PULSE    , ChargeMove.GUNK_SHOT           , ChargeMove.SLUDGE_WAVE                                                                                                                     }),
	NIDOKING  (new Type[] {Type.POISON  , Type.GROUND  }, 162, 204, 170, new BasicMove[] {BasicMove.FURY_CUTTER   , BasicMove.POISON_JAB         }, new ChargeMove[] {ChargeMove.EARTHQUAKE    , ChargeMove.MEGAHORN            , ChargeMove.SLUDGE_WAVE                                                                                                                     }),
	NIDOQUEEN (new Type[] {Type.POISON  , Type.GROUND  }, 180, 184, 190, new BasicMove[] {BasicMove.BITE          , BasicMove.POISON_JAB         }, new ChargeMove[] {ChargeMove.EARTHQUAKE    , ChargeMove.SLUDGE_WAVE         , ChargeMove.STONE_EDGE                                                                                                                      }),
	NIDORAN_F (new Type[] {Type.POISON  , Type.NONE    }, 110, 100, 104, new BasicMove[] {BasicMove.BITE          , BasicMove.POISON_STING       }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.POISON_FANG         , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	NIDORAN_M (new Type[] {Type.POISON  , Type.NONE    }, 92 , 110, 94 , new BasicMove[] {BasicMove.PECK          , BasicMove.POISON_STING       }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.HORN_ATTACK         , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	NIDORINA  (new Type[] {Type.POISON  , Type.NONE    }, 140, 132, 136, new BasicMove[] {BasicMove.BITE          , BasicMove.POISON_STING       }, new ChargeMove[] {ChargeMove.DIG           , ChargeMove.POISON_FANG         , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	NIDORINO  (new Type[] {Type.POISON  , Type.NONE    }, 122, 142, 128, new BasicMove[] {BasicMove.POISON_JAB    , BasicMove.POISON_STING       }, new ChargeMove[] {ChargeMove.DIG           , ChargeMove.HORN_ATTACK         , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	NINETALES (new Type[] {Type.FIRE    , Type.NONE    }, 146, 176, 194, new BasicMove[] {BasicMove.EMBER         , BasicMove.FEINT_ATTACK       }, new ChargeMove[] {ChargeMove.FIRE_BLAST    , ChargeMove.FLAMETHROWER        , ChargeMove.HEAT_WAVE                                                                                                                       }),
	ODDISH    (new Type[] {Type.GRASS   , Type.POISON  }, 90 , 134, 130, new BasicMove[] {BasicMove.ACID          , BasicMove.RAZOR_LEAF         }, new ChargeMove[] {ChargeMove.MOONBLAST     , ChargeMove.SEED_BOMB           , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	OMANYTE   (new Type[] {Type.ROCK    , Type.WATER   }, 70 , 132, 160, new BasicMove[] {BasicMove.MUD_SHOT      , BasicMove.WATER_GUN          }, new ChargeMove[] {ChargeMove.ANCIENT_POWER , ChargeMove.BRINE               , ChargeMove.ROCK_TOMB                                                                                                                       }),
	OMASTAR   (new Type[] {Type.ROCK    , Type.WATER   }, 140, 180, 202, new BasicMove[] {BasicMove.MUD_SHOT      , BasicMove.WATER_GUN          }, new ChargeMove[] {ChargeMove.ANCIENT_POWER , ChargeMove.HYDRO_PUMP          , ChargeMove.ROCK_SLIDE                                                                                                                      }),
	ONIX      (new Type[] {Type.ROCK    , Type.GROUND  }, 70 , 90 , 186, new BasicMove[] {BasicMove.ROCK_THROW    , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.IRON_HEAD     , ChargeMove.ROCK_SLIDE          , ChargeMove.STONE_EDGE                                                                                                                      }),
	PARAS     (new Type[] {Type.BUG     , Type.GRASS   }, 70 , 122, 120, new BasicMove[] {BasicMove.BUG_BITE      , BasicMove.SCRATCH            }, new ChargeMove[] {ChargeMove.CROSS_POISON  , ChargeMove.SEED_BOMB           , ChargeMove.X_SCISSOR                                                                                                                       }),
	PARASECT  (new Type[] {Type.BUG     , Type.GRASS   }, 120, 162, 170, new BasicMove[] {BasicMove.BUG_BITE      , BasicMove.FURY_CUTTER        }, new ChargeMove[] {ChargeMove.CROSS_POISON  , ChargeMove.SOLAR_BEAM          , ChargeMove.X_SCISSOR                                                                                                                       }),
	PERSIAN   (new Type[] {Type.NORMAL  , Type.NONE    }, 130, 156, 146, new BasicMove[] {BasicMove.FEINT_ATTACK  , BasicMove.SCRATCH            }, new ChargeMove[] {ChargeMove.NIGHT_SLASH   , ChargeMove.PLAY_ROUGH          , ChargeMove.POWER_GEM                                                                                                                       }),
	PIDGEOT   (new Type[] {Type.NORMAL  , Type.FLYING  }, 166, 170, 166, new BasicMove[] {BasicMove.STEEL_WING    , BasicMove.WING_ATTACK        }, new ChargeMove[] {ChargeMove.AERIAL_ACE    , ChargeMove.AIR_CUTTER          , ChargeMove.HURRICANE                                                                                                                       }),
	PIDGEOTTO (new Type[] {Type.NORMAL  , Type.FLYING  }, 126, 126, 122, new BasicMove[] {BasicMove.STEEL_WING    , BasicMove.WING_ATTACK        }, new ChargeMove[] {ChargeMove.AERIAL_ACE    , ChargeMove.AIR_CUTTER          , ChargeMove.TWISTER                                                                                                                         }),
	PIDGEY    (new Type[] {Type.NORMAL  , Type.FLYING  }, 80 , 94 , 90 , new BasicMove[] {BasicMove.QUICK_ATTACK  , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.AERIAL_ACE    , ChargeMove.AIR_CUTTER          , ChargeMove.TWISTER                                                                                                                         }),
	PIKACHU   (new Type[] {Type.ELECTRIC, Type.NONE    }, 70 , 124, 108, new BasicMove[] {BasicMove.QUICK_ATTACK  , BasicMove.THUNDER_SHOCK      }, new ChargeMove[] {ChargeMove.DISCHARGE     , ChargeMove.THUNDER             , ChargeMove.THUNDERBOLT                                                                                                                     }),
	PINSIR    (new Type[] {Type.BUG     , Type.NONE    }, 130, 184, 186, new BasicMove[] {BasicMove.FURY_CUTTER   , BasicMove.ROCK_SMASH         }, new ChargeMove[] {ChargeMove.SUBMISSION    , ChargeMove.VICE_GRIP           , ChargeMove.X_SCISSOR                                                                                                                       }),
	POLIWAG   (new Type[] {Type.WATER   , Type.NONE    }, 80 , 108, 98 , new BasicMove[] {BasicMove.BUBBLE        , BasicMove.MUD_SHOT           }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.BUBBLE_BEAM         , ChargeMove.MUD_BOMB                                                                                                                        }),
	POLIWHIRL (new Type[] {Type.WATER   , Type.NONE    }, 130, 132, 132, new BasicMove[] {BasicMove.BUBBLE        , BasicMove.MUD_SHOT           }, new ChargeMove[] {ChargeMove.BUBBLE_BEAM   , ChargeMove.MUD_BOMB            , ChargeMove.SCALD                                                                                                                           }),
	POLIWRATH (new Type[] {Type.WATER   , Type.FIGHTING}, 180, 180, 202, new BasicMove[] {BasicMove.BUBBLE        , BasicMove.MUD_SHOT           }, new ChargeMove[] {ChargeMove.HYDRO_PUMP    , ChargeMove.ICE_PUNCH           , ChargeMove.SUBMISSION                                                                                                                      }),
	PONYTA    (new Type[] {Type.FIRE    , Type.NONE    }, 100, 168, 138, new BasicMove[] {BasicMove.EMBER         , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.FIRE_BLAST    , ChargeMove.FLAME_CHARGE        , ChargeMove.FLAME_WHEEL                                                                                                                     }),
	PORYGON   (new Type[] {Type.NORMAL  , Type.NONE    }, 130, 156, 158, new BasicMove[] {BasicMove.ZEN_HEADBUTT  , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.DISCHARGE     , ChargeMove.PSYBEAM             , ChargeMove.SIGNAL_BEAM                                                                                                                     }),
	PRIMEAPE  (new Type[] {Type.FIGHTING, Type.NONE    }, 130, 178, 150, new BasicMove[] {BasicMove.KARATE_CHOP   , BasicMove.LOW_KICK           }, new ChargeMove[] {ChargeMove.CROSS_CHOP    , ChargeMove.LOW_SWEEP           , ChargeMove.NIGHT_SLASH                                                                                                                     }),
	PSYDUCK   (new Type[] {Type.WATER   , Type.NONE    }, 100, 132, 112, new BasicMove[] {BasicMove.WATER_GUN     , BasicMove.ZEN_HEADBUTT       }, new ChargeMove[] {ChargeMove.AQUA_TAIL     , ChargeMove.CROSS_CHOP          , ChargeMove.PSYBEAM                                                                                                                         }),
	RAICHU    (new Type[] {Type.ELECTRIC, Type.NONE    }, 120, 200, 154, new BasicMove[] {BasicMove.SPARK         , BasicMove.THUNDER_SHOCK      }, new ChargeMove[] {ChargeMove.BRICK_BREAK   , ChargeMove.THUNDER             , ChargeMove.THUNDER_PUNCH                                                                                                                   }),
	RAPIDASH  (new Type[] {Type.FIRE    , Type.NONE    }, 130, 200, 170, new BasicMove[] {BasicMove.EMBER         , BasicMove.LOW_KICK           }, new ChargeMove[] {ChargeMove.DRILL_RUN     , ChargeMove.FIRE_BLAST          , ChargeMove.HEAT_WAVE                                                                                                                       }),
	RATICATE  (new Type[] {Type.NORMAL  , Type.NONE    }, 110, 146, 150, new BasicMove[] {BasicMove.BITE          , BasicMove.QUICK_ATTACK       }, new ChargeMove[] {ChargeMove.DIG           , ChargeMove.HYPER_BEAM          , ChargeMove.HYPER_FANG                                                                                                                      }),
	RATTATA   (new Type[] {Type.NORMAL  , Type.NONE    }, 60 , 92 , 86 , new BasicMove[] {BasicMove.QUICK_ATTACK  , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.DIG                 , ChargeMove.HYPER_FANG                                                                                                                      }),
	RHYDON    (new Type[] {Type.GROUND  , Type.ROCK    }, 210, 166, 160, new BasicMove[] {BasicMove.MUD_SLAP      , BasicMove.ROCK_SMASH         }, new ChargeMove[] {ChargeMove.EARTHQUAKE    , ChargeMove.MEGAHORN            , ChargeMove.STONE_EDGE                                                                                                                      }),
	RHYHORN   (new Type[] {Type.GROUND  , Type.ROCK    }, 160, 110, 116, new BasicMove[] {BasicMove.MUD_SLAP      , BasicMove.ROCK_SMASH         }, new ChargeMove[] {ChargeMove.BULLDOZE      , ChargeMove.HORN_ATTACK         , ChargeMove.STOMP                                                                                                                           }),
	SANDSHREW (new Type[] {Type.GROUND  , Type.NONE    }, 100, 90 , 114, new BasicMove[] {BasicMove.MUD_SHOT      , BasicMove.SCRATCH            }, new ChargeMove[] {ChargeMove.DIG           , ChargeMove.ROCK_SLIDE          , ChargeMove.ROCK_TOMB                                                                                                                       }),
	SANDSLASH (new Type[] {Type.GROUND  , Type.NONE    }, 150, 150, 172, new BasicMove[] {BasicMove.METAL_CLAW    , BasicMove.MUD_SHOT           }, new ChargeMove[] {ChargeMove.BULLDOZE      , ChargeMove.EARTHQUAKE          , ChargeMove.ROCK_TOMB                                                                                                                       }),
	SCYTHER   (new Type[] {Type.BUG     , Type.FLYING  }, 140, 176, 180, new BasicMove[] {BasicMove.FURY_CUTTER   , BasicMove.STEEL_WING         }, new ChargeMove[] {ChargeMove.BUG_BUZZ      , ChargeMove.NIGHT_SLASH         , ChargeMove.X_SCISSOR                                                                                                                       }),
	SEADRA    (new Type[] {Type.WATER   , Type.NONE    }, 110, 176, 150, new BasicMove[] {BasicMove.DRAGON_BREATH , BasicMove.WATER_GUN          }, new ChargeMove[] {ChargeMove.BLIZZARD      , ChargeMove.DRAGON_PULSE        , ChargeMove.HYDRO_PUMP                                                                                                                      }),
	SEAKING   (new Type[] {Type.WATER   , Type.NONE    }, 160, 172, 160, new BasicMove[] {BasicMove.PECK          , BasicMove.POISON_JAB         }, new ChargeMove[] {ChargeMove.DRILL_RUN     , ChargeMove.ICY_WIND            , ChargeMove.MEGAHORN                                                                                                                        }),
	SEEL      (new Type[] {Type.WATER   , Type.NONE    }, 130, 104, 138, new BasicMove[] {BasicMove.ICE_SHARD     , BasicMove.LICK               }, new ChargeMove[] {ChargeMove.AQUA_JET      , ChargeMove.AQUA_TAIL           , ChargeMove.ICY_WIND                                                                                                                        }),
	SHELLDER  (new Type[] {Type.WATER   , Type.NONE    }, 60 , 120, 112, new BasicMove[] {BasicMove.ICE_SHARD     , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.BUBBLE_BEAM   , ChargeMove.ICY_WIND            , ChargeMove.WATER_PULSE                                                                                                                     }),
	SLOWBRO   (new Type[] {Type.WATER   , Type.PSYCHIC }, 190, 184, 198, new BasicMove[] {BasicMove.CONFUSION     , BasicMove.WATER_GUN          }, new ChargeMove[] {ChargeMove.ICE_BEAM      , ChargeMove.PSYCHIC             , ChargeMove.WATER_PULSE                                                                                                                     }),
	SLOWPOKE  (new Type[] {Type.WATER   , Type.PSYCHIC }, 180, 110, 110, new BasicMove[] {BasicMove.CONFUSION     , BasicMove.WATER_GUN          }, new ChargeMove[] {ChargeMove.PSYCHIC       , ChargeMove.PSYSHOCK            , ChargeMove.WATER_PULSE                                                                                                                     }),
	SNORLAX   (new Type[] {Type.NORMAL  , Type.NONE    }, 320, 180, 180, new BasicMove[] {BasicMove.LICK          , BasicMove.ZEN_HEADBUTT       }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.EARTHQUAKE          , ChargeMove.HYPER_BEAM                                                                                                                      }),
	SPEAROW   (new Type[] {Type.NORMAL  , Type.FLYING  }, 80 , 102, 78 , new BasicMove[] {BasicMove.PECK          , BasicMove.QUICK_ATTACK       }, new ChargeMove[] {ChargeMove.AERIAL_ACE    , ChargeMove.DRILL_PECK          , ChargeMove.TWISTER                                                                                                                         }),
	SQUIRTLE  (new Type[] {Type.WATER   , Type.NONE    }, 88 , 112, 142, new BasicMove[] {BasicMove.BUBBLE        , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.AQUA_JET      , ChargeMove.AQUA_TAIL           , ChargeMove.WATER_PULSE                                                                                                                     }),
	STARMIE   (new Type[] {Type.WATER   , Type.PSYCHIC }, 120, 194, 192, new BasicMove[] {BasicMove.TACKLE        , BasicMove.WATER_GUN          }, new ChargeMove[] {ChargeMove.HYDRO_PUMP    , ChargeMove.POWER_GEM           , ChargeMove.PSYBEAM                                                                                                                         }),
	STARYU    (new Type[] {Type.WATER   , Type.NONE    }, 60 , 130, 128, new BasicMove[] {BasicMove.TACKLE        , BasicMove.WATER_GUN          }, new ChargeMove[] {ChargeMove.BUBBLE_BEAM   , ChargeMove.POWER_GEM           , ChargeMove.SWIFT                                                                                                                           }),
	TANGELA   (new Type[] {Type.GRASS   , Type.NONE    }, 130, 164, 152, new BasicMove[] {BasicMove.VINE_WHIP                                    }, new ChargeMove[] {ChargeMove.POWER_WHIP    , ChargeMove.SLUDGE_BOMB         , ChargeMove.SOLAR_BEAM                                                                                                                      }),
	TAUROS    (new Type[] {Type.NORMAL  , Type.NONE    }, 150, 148, 184, new BasicMove[] {BasicMove.TACKLE        , BasicMove.ZEN_HEADBUTT       }, new ChargeMove[] {ChargeMove.EARTHQUAKE    , ChargeMove.HORN_ATTACK         , ChargeMove.IRON_HEAD                                                                                                                       }),
	TENTACOOL (new Type[] {Type.WATER   , Type.POISON  }, 80 , 106, 136, new BasicMove[] {BasicMove.BUBBLE        , BasicMove.POISON_STING       }, new ChargeMove[] {ChargeMove.BUBBLE_BEAM   , ChargeMove.WATER_PULSE         , ChargeMove.WRAP                                                                                                                            }),
	TENTACRUEL(new Type[] {Type.WATER   , Type.POISON  }, 160, 170, 196, new BasicMove[] {BasicMove.ACID          , BasicMove.POISON_JAB         }, new ChargeMove[] {ChargeMove.BLIZZARD      , ChargeMove.HYDRO_PUMP          , ChargeMove.SLUDGE_WAVE                                                                                                                     }),
	VAPOREON  (new Type[] {Type.WATER   , Type.NONE    }, 260, 186, 168, new BasicMove[] {BasicMove.WATER_GUN                                    }, new ChargeMove[] {ChargeMove.AQUA_TAIL     , ChargeMove.HYDRO_PUMP          , ChargeMove.WATER_PULSE                                                                                                                     }),
	VENOMOTH  (new Type[] {Type.BUG     , Type.POISON  }, 140, 172, 154, new BasicMove[] {BasicMove.BUG_BITE      , BasicMove.CONFUSION          }, new ChargeMove[] {ChargeMove.BUG_BUZZ      , ChargeMove.POISON_FANG         , ChargeMove.PSYCHIC                                                                                                                         }),
	VENONAT   (new Type[] {Type.BUG     , Type.POISON  }, 120, 108, 118, new BasicMove[] {BasicMove.BUG_BITE      , BasicMove.CONFUSION          }, new ChargeMove[] {ChargeMove.POISON_FANG   , ChargeMove.PSYBEAM             , ChargeMove.SIGNAL_BEAM                                                                                                                     }),
	VENUSAUR  (new Type[] {Type.GRASS   , Type.POISON  }, 160, 198, 200, new BasicMove[] {BasicMove.RAZOR_LEAF    , BasicMove.VINE_WHIP          }, new ChargeMove[] {ChargeMove.PETAL_BLIZZARD, ChargeMove.SLUDGE_BOMB         , ChargeMove.SOLAR_BEAM                                                                                                                      }),
	VICTREEBEL(new Type[] {Type.GRASS   , Type.POISON  }, 160, 222, 152, new BasicMove[] {BasicMove.ACID          , BasicMove.RAZOR_LEAF         }, new ChargeMove[] {ChargeMove.LEAF_BLADE    , ChargeMove.SLUDGE_BOMB         , ChargeMove.SOLAR_BEAM                                                                                                                      }),
	VILEPLUME (new Type[] {Type.GRASS   , Type.POISON  }, 150, 202, 190, new BasicMove[] {BasicMove.ACID          , BasicMove.RAZOR_LEAF         }, new ChargeMove[] {ChargeMove.MOONBLAST     , ChargeMove.PETAL_BLIZZARD      , ChargeMove.SOLAR_BEAM                                                                                                                      }),
	VOLTORB   (new Type[] {Type.ELECTRIC, Type.NONE    }, 80 , 102, 124, new BasicMove[] {BasicMove.SPARK         , BasicMove.TACKLE             }, new ChargeMove[] {ChargeMove.DISCHARGE     , ChargeMove.SIGNAL_BEAM         , ChargeMove.THUNDERBOLT                                                                                                                     }),
	VULPIX    (new Type[] {Type.FIRE    , Type.NONE    }, 76 , 106, 118, new BasicMove[] {BasicMove.EMBER         , BasicMove.QUICK_ATTACK       }, new ChargeMove[] {ChargeMove.BODY_SLAM     , ChargeMove.FLAME_CHARGE        , ChargeMove.FLAMETHROWER                                                                                                                    }),
	WARTORTLE (new Type[] {Type.WATER   , Type.NONE    }, 118, 144, 176, new BasicMove[] {BasicMove.BITE          , BasicMove.WATER_GUN          }, new ChargeMove[] {ChargeMove.AQUA_JET      , ChargeMove.HYDRO_PUMP          , ChargeMove.ICE_BEAM                                                                                                                        }),
	WEEDLE    (new Type[] {Type.BUG     , Type.POISON  }, 80 , 68 , 64 , new BasicMove[] {BasicMove.BUG_BITE      , BasicMove.POISON_STING       }, new ChargeMove[] {ChargeMove.STRUGGLE                                                                                                                                                                                    }),
	WEEPINBELL(new Type[] {Type.GRASS   , Type.POISON  }, 130, 190, 110, new BasicMove[] {BasicMove.ACID          , BasicMove.RAZOR_LEAF         }, new ChargeMove[] {ChargeMove.POWER_WHIP    , ChargeMove.SEED_BOMB           , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	WEEZING   (new Type[] {Type.POISON  , Type.NONE    }, 130, 190, 198, new BasicMove[] {BasicMove.TACKLE                                       }, new ChargeMove[] {ChargeMove.DARK_PULSE    , ChargeMove.SHADOW_BALL         , ChargeMove.SLUDGE_BOMB                                                                                                                     }),
	WIGGLYTUFF(new Type[] {Type.NORMAL  , Type.FAIRY   }, 280, 168, 108, new BasicMove[] {BasicMove.FEINT_ATTACK  , BasicMove.POUND              }, new ChargeMove[] {ChargeMove.DAZZLING_GLEAM, ChargeMove.HYPER_BEAM          , ChargeMove.PLAY_ROUGH                                                                                                                      }),
	ZAPDOS    (new Type[] {Type.ELECTRIC, Type.FLYING  }, 180, 232, 194, new BasicMove[] {BasicMove.THUNDER_SHOCK                                }, new ChargeMove[] {ChargeMove.DISCHARGE     , ChargeMove.THUNDER             , ChargeMove.THUNDERBOLT                                                                                                                     }),
	ZUBAT     (new Type[] {Type.POISON  , Type.FLYING  }, 80 , 88 , 90 , new BasicMove[] {BasicMove.BITE          , BasicMove.QUICK_ATTACK       }, new ChargeMove[] {ChargeMove.AIR_CUTTER    , ChargeMove.POISON_FANG         , ChargeMove.SLUDGE_BOMB                                                                                                                     });
	
	private final Type[] type;
	private final BasicMove[] basicMoves;
	private final ChargeMove[] chargeMoves;
	private final int stamina;
	private final int attack;
	private final int defense;
	
	private Species(Type[] type, int stamina, int attack, int defense, BasicMove[] basicMoves, ChargeMove[] chargeMoves) {
		this.type = type;
		this.basicMoves = basicMoves;
		this.chargeMoves = chargeMoves;
		this.stamina = stamina;
		this.attack = attack;
		this.defense = defense;
	}

	public Type[] getType() {
		return type;
	}

	public BasicMove[] getBasicMoves() {
		return basicMoves;
	}
	
	public ChargeMove[] getChargeMoves() {
		return chargeMoves;
	}

	public boolean canUse(BasicMove basicMove) {
		for (int i = 0; i < this.basicMoves.length; i++) {
			if (basicMove == this.basicMoves[i]) {
				return true;
			}
		}
		return false;
	}

	public boolean canUse(ChargeMove chargeMove) {
		for (int i = 0; i < this.chargeMoves.length; i++) {
			if (chargeMove == this.chargeMoves[i]) {
				return true;
			}
		}
		return false;
	}
	
	public int getStamina() {
		return stamina;
	}

	public int getAttack() {
		return attack;
	}

	public int getDefense() {
		return defense;
	}
	
}
